{
 "title": "Long Queries",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   { "name": "LongQueryId", "label": "Long Query Id" }
  ]
 },
 "panels": [
  {
   "title": "Long Queries over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for long queries count\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT [time]=event_time, [Long queries] = count(distinct session_id)\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_xes_long_queries]\n     where [sql_instance] = ''$sql_instance''\n   AND $__timeFilter(event_time)\n   GROUP BY event_time\nORDER BY time desc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Long Queries Details",
   "type": "table",
   "description": "Click on the row or long_query_id column to display SQL Text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for long queries details\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT *\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_xes_long_queries]\n     where [sql_instance] = ''$sql_instance''\n   AND $__timeFilter(event_time)\nORDER BY event_time desc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Query Text",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for specific long query details\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT time=getdate(),sql_text, statement\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_xes_long_queries]\n     where [sql_instance] = ''$sql_instance''\n   AND $__timeFilter(event_time)\n   AND long_query_id = isnull(''$LongQueryId'',-1)'\n\nEXEC sp_executesql @sql"
    }
   ]
  }
 ]
}