{
 "title": "SQL Instance Overview",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Repository", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   { "name": "aggregation", "label": "Aggregation", "query": "1s,1m,1h,1d" },
   { "name": "Waits", "label": "Waits By", "query": "Category,Type" },
   { "name": "WaitCalc", "label": "Wait Calculation", "query": "ms/sec,Delta" },
   { "name": "ShowChecksOK", "label": "Show OK Checks", "query": "Yes,No" },
   {
    "name": "sql_version",
    "label": "SQL Version",
    "query": "select [sql_version]\n  FROM [dbo].[sqlwatch_meta_server]\n  WHERE servername = '$sql_instance'"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select database_name from [dbo].[sqlwatch_meta_database] where sql_instance = '$sql_instance'"
   },
   {
    "name": "baseline",
    "label": "Baseline",
    "query": "select [baseline] = 'None'\nunion all\nselect [baseline] = '-1h'\nunion all\nselect [baseline] = '-1d'\nunion all\nselect [baseline] = '-1w'\nunion all\nselect [baseline] = 'Daily'\nunion all\nSELECT [baseline] = 'User Baseline: ' + convert(varchar(100),[baseline_id])\nFROM [dbo].[sqlwatch_meta_baseline]\nWHERE sql_instance = '$sql_instance'"
   },
   { "name": "currentrequests", "label": "Requests", "query": "Current,All" }
  ]
 },
 "panels": [
  {
   "title": "$sql_instance: SQL Server Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<br><br><h1 id=\"overview\">Overview</h1>\r\n<p>This dashboard was designed to help you understand what happens in your SQL Server and help you find bottlenecks. A single page view helps correlate various events and makes it easier to spot trends. Like most computer systems, SQL Server relies on the following components to perform well: <b>CPU > Memory > Storage > Network</b>.\r\nIf any of these does not perform well, we may be seeing performance degradation in our database and/or application. We start looking at the tiles from left to right. Although the data flows from right to left (Storage to CPU), in case of slow disks, we may be seeing long latencies, lots of disk tranfers and long Pending Queue and not a lot of CPU activity. In case of poorly optimised queries or general workload problems, we may be seeing lots of CPU activity but not a lot of disk activity.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<h1><b><big>$sql_instance</big></b></h1>\r\n<p>$sql_version</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 269 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 102 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server based on instance selection\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT \n      [time] = snapshot_time\n      ,[Pending] = sum([runnable_tasks_count]+work_queue_count+pending_disk_io_count)\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_perf_os_schedulers]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n    and snapshot_time >= dateadd(minute,-15,getutcdate())\n  AND [sql_instance] = ''$sql_instance''\n  GROUP BY snapshot_time\nORDER BY time ASC'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 296 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for blocking sessions\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT time = isnull(x.event_time,h.snapshot_time)\n      ,[Blocked] = sum(case when isnull(blocking_session_id,0) > 0 then 1 else 0 end)\n  from [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_logger_snapshot_header] h\n  left join [' + @linked_server_name + '].[' + @database_name + '].[dbo].[ufn_sqlwatch_get_blocking_chains] ($__timeFrom(), $__timeTo(),''$sql_instance'') x\n  on h.snapshot_time = x.snapshot_time\n  and h.snapshot_type_id = x.snapshot_type_id\n  and h.sql_instance = x.sql_instance\n  where h.sql_instance = ''$sql_instance''\n  and h.snapshot_type_id = 9\n  and $__timeFilter(h.snapshot_time)\n  group by isnull(x.event_time,h.snapshot_time)\n  order by time asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for memory metrics\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT \n      [time] = snapshot_time\n      ,[Memory] = AVG([physical_memory_in_use_kb]*1.0/([physical_memory_in_use_kb]+[available_commit_limit_kb]))\n      ,[Memory Low] = case when convert(int,process_physical_memory_low)+convert(int,process_virtual_memory_low) > 0 then 1 else 0 end\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_perf_os_process_memory]\n  WHERE 1 = 1\n  AND  $__timeFilter(snapshot_time)\n      and snapshot_time >= dateadd(minute,-15,getutcdate())\n  AND [sql_instance] = ''$sql_instance''\n  GROUP BY snapshot_time\n  , case when convert(int,process_physical_memory_low)+convert(int,process_virtual_memory_low) > 0 then 1 else 0 end\nORDER BY time ASC'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for checks status\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT time=getdate(),t.last_check_status,last_check_status_count=count(c.last_check_status)\n  FROM (\n    select last_check_status=''OK'' union all \n    select last_check_status = ''WARNING'' union all \n    select last_check_status = ''CRITICAL'' union all \n    select last_check_status = ''CHECK ERROR'') t\n\n\touter apply (\n\t\tselect last_check_status = case when last_check_status is null then ''CHECK ERROR'' else last_check_status end\n\t\tfrom [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_meta_check] mc\n\t\twhere [sql_instance] =  ''$sql_instance''\n\t\tand case when last_check_status is null then ''CHECK ERROR'' else last_check_status end = t.last_check_status\n\t\tand check_enabled = 1\n\t\t) c\ngroup by t.last_check_status\norder by case t.last_check_status when  ''OK'' then 1 when ''WARNING'' then 2 when ''CRITICAL'' then 3 else 4 end'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for performance counters\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nselect \n\t  time = pc.snapshot_time\n\t, ''CPU usage %'' = sum(case \n\t      when 1=1 and mpc.counter_name = ''Processor Time %'' then pc.[cntr_value_calculated] \n\t      else null end)\n\t, ''Batch Requests/sec'' = avg(case when mpc.counter_name = ''Batch Requests/sec'' then pc.[cntr_value_calculated] else null end)\n\t, ''Logins/sec'' = avg(case when mpc.counter_name = ''Logins/sec'' then pc.[cntr_value_calculated] else null end)\n\t, ''Transactions/sec'' = sum(case when mpc.counter_name = ''Transactions/sec'' and pc.instance_name not in (''_Total'',''mssqlsystemresource'') then pc.[cntr_value_calculated] else null end)\n\t, ''User Connections'' = avg(case when mpc.counter_name = ''User Connections'' then pc.[cntr_value_calculated] else null end)\n\t, ''SQL Compilations/sec'' = avg(case when mpc.counter_name = ''SQL Compilations/sec'' then pc.[cntr_value_calculated] else null end)\n\t, ''Availability Group Bytes'' = avg(case when mpc.counter_name in (''Bytes Sent to Replica/sec'',''Bytes Received from Replica/sec'') then pc.[cntr_value_calculated] else null end)\n  ,''Connection Memory (KB)'' = avg(case when mpc.counter_name = ''Connection Memory (KB)'' then pc.[cntr_value_calculated] else null end)\n  ,''Optimizer Memory (KB)'' = avg(case when mpc.counter_name = ''Optimizer Memory (KB)'' then pc.[cntr_value_calculated] else null end)\n  ,''SQL Cache Memory (KB)'' = avg(case when mpc.counter_name = ''SQL Cache Memory (KB)'' then pc.[cntr_value_calculated] else null end)\n  ,''Total Server Memory (KB)'' = avg(case when mpc.counter_name = ''Total Server Memory (KB)'' then pc.[cntr_value_calculated] else null end)\n  ,''Stolen Server Memory (KB)'' = avg(case when mpc.counter_name = ''Stolen Server Memory (KB)'' then pc.[cntr_value_calculated] else null end)\n  ,''Target Server Memory (KB)'' = avg(case when mpc.counter_name = ''Target Server Memory (KB)'' then pc.[cntr_value_calculated] else null end)\nfrom [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_logger_perf_os_performance_counters] pc\ninner join [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_meta_performance_counter] mpc\n\ton pc.sql_instance = mpc.sql_instance\n\tand pc.performance_counter_id = mpc.performance_counter_id\nwhere $__timeFilter(pc.snapshot_time)\nand pc.snapshot_time >= dateadd(minute,-15,getutcdate())\nand pc.[sql_instance] = ''$sql_instance''\nand mpc.counter_name in (''CPU usage %'', ''Batch Requests/sec'', ''Logins/sec'', ''Transactions/sec'', ''User Connections'', ''SQL Compilations/sec'', ''Bytes Sent to Replica/sec'', ''Bytes Received from Replica/sec'', ''Processor Time %'', ''% Processor Time'', ''Connection Memory (KB)'', ''Optimizer Memory (KB)'', ''SQL Cache Memory (KB)'', ''Total Server Memory (KB)'', ''Stolen Server Memory (KB)'', ''Target Server Memory (KB)'')\ngroup by pc.snapshot_time\norder by time asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Top Waits by Total Time",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for wait stats\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT \n      [time] = snapshot_time\n      ,[Wait Type] = case when len([wait])>19 then left([wait],19) + ''...'' else [wait] end\n      ,[Wait Time] = sum([wait_time_ms_per_second]) \n  FROM (SELECT wait_time_ms_per_second, wait= case when ''$Waits'' = ''Category'' then [wait_category] else LOWER([wait_type]) end, snapshot_time, RN=ROW_NUMBER() over (partition by wait_category order by wait_time_ms_per_second desc)\n    FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_perf_os_wait_stats] \n      WHERE 1=1\n      AND $__timeFilter(snapshot_time)\n        and snapshot_time >= dateadd(minute,-15,getutcdate())\n      AND [sql_instance] = ''$sql_instance''\n  ) t\n  WHERE 1=1\n  GROUP BY case when len([wait])>19 then left([wait],19) + ''...'' else [wait] end\n      ,snapshot_time\nORDER BY time asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for sessions stats\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT time = r1.snapshot_time\n      ,[running] = avg(running)\n      ,[sleeping] = avg(sleeping)\n      ,[dormant] = avg(dormant)\n      ,[preconnect] = avg(preconnect)\n      ,[cpu_time] = avg(cpu_time)\n      ,[reads] = avg(reads)\n      ,[writes] = avg(writes)\n      ,  type = case when type = 1 then ''User'' else ''System'' end\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_logger_dm_exec_sessions_stats] r1 (nolock)\n\twhere $__timeFilter(r1.snapshot_time)\n  and snapshot_time > dateadd(minute,-15,GETUTCDATE())\t\n  and r1.sql_instance = ''$sql_instance''\n  group by r1.snapshot_time, case when type = 1 then ''User'' else ''System'' end\n  order by time asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "User Requests",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for user requests\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT time = r1.snapshot_time\n      ,  Background\t= background\n      ,  Running = running\n      ,  Runnable = runnable\n      ,  Sleeping\t = sleeping\n      ,  Suspended\t = suspended\n      ,  Waiting\t = waiting_tasks\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_logger_dm_exec_requests_stats] r1 (nolock)\n\twhere $__timeFilter(r1.snapshot_time)\n\tand type = 1\n\tand r1.snapshot_time > dateadd(minute,-15,getutcdate())\n  and r1.sql_instance = ''$sql_instance''\n    order by time asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "SQL Memory",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 269 }
   ]
  },
  {
   "title": "Disk IO",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for file stats\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT \n      [time] = snapshot_time \n      ,[Latency Reads] = MAX(fs.[io_latency_read])\n      ,[Latency Writes] = MAX(fs.[io_latency_write])\n  \t  ,[Reads IO] = AVG(fs.bytes_read_per_second)\n  \t  ,[Writes IO] = AVG(fs.bytes_written_per_second)\n      ,[Disk] = left(upper([file_physical_name]),2) + '' '' + isnull(v.label,'''')\n      ,[Max Latency] = max(case when fs.[io_latency_read] > fs.[io_latency_write] then fs.[io_latency_read] else fs.[io_latency_write] end) over (partition by snapshot_time )\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_perf_file_stats] fs\n  outer apply (\n    select top 1 label \n    from [' + @linked_server_name + '].[' + @database_name + '].[dbo].[sqlwatch_meta_os_volume] v\n\t  where v.volume_name = left(fs.file_physical_name,3)) v\n  WHERE 1 = 1\n  AND $__timeFilter(fs.snapshot_time)\n    and snapshot_time >= dateadd(minute,-15,getutcdate())\n  AND [sql_instance] = ''$sql_instance''\n  AND database_name IN ($database)\n  GROUP BY fs.snapshot_time \n  , left(upper([file_physical_name]),2) + '' '' + isnull(v.label,'''')\n  ,case when fs.[io_latency_read] > fs.[io_latency_write] then fs.[io_latency_read] else fs.[io_latency_write] end\nORDER BY time ASC'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Checks",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for check details\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT  top 15 time=isnull(last_check_date,getutcdate()),[check_name] = CASE WHEN LEN([check_name]) > 28 THEN LEFT(check_name,27) + ''...'' ELSE [check_name] END\n        ,status = CASE [last_check_status] \n        WHEN ''CRITICAL'' THEN 2\n        WHEN ''WARNING'' THEN 1\n        WHEN ''OK'' THEN 0\n        ELSE 3 END\n  FROM (select last_check_date , check_name = (replace(replace([check_name],''Database'',''''),'' failure count'',''''))\n    , last_check_status = case when last_check_status is null then ''CHECK ERROR'' else last_check_status end\n  from [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_dim_check] with (nolock)\n  WHERE  [target_sql_instance] = ''$sql_instance''\n  AND check_enabled = 1\n  ) t\n  where last_check_status <> ''ok''\n  order by case when last_check_status = ''OK'' then dateadd(month,-12,last_check_date) else isnull(last_check_date,getutcdate()) end asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "options": { "content": " " },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n\t  s.servername\r\n\t, 'All Databases' = [Databases]\r\n\t, 'Total Data Size' = [Data Size]\r\n\t, 'Total Growth Per Day' = [Growth per day]\r\n\t, 'All Agent Jobs' = [Jobs]\r\nfrom dbo.sqlwatch_meta_server s\r\n\r\nouter apply (\r\n\tselect\r\n\t  [Databases]=count(db.database_name)\r\n\t, [Data Size]=sum([database_size_bytes_current])\r\n\t, [Growth per day]=sum(database_growth_bytes_per_day)\r\n\tfrom [dbo].[vw_sqlwatch_report_dim_database] db\r\n\twhere db.sql_instance = s.sql_instance\r\n) dbs\r\n\r\nouter apply (\r\n\tselect \r\n\t\t[Jobs]=count(jb.job_name)\r\n\tfrom [dbo].[vw_sqlwatch_report_dim_agent_job] jb\r\n\twhere jb.sql_instance = s.sql_instance\r\n) jbs"
    },
    {
     "rawSql": "select \r\n\t  s.servername\r\n\t, 'SQLWATCH Data Size' = [Data Size]\r\n\t, 'SQLWATCH Growth Per Day' = [Growth per day]\r\nfrom dbo.sqlwatch_meta_server s\r\n\r\nouter apply (\r\n\tselect\r\n\t  [Databases]=count(db.database_name)\r\n\t, [Data Size]=sum([database_size_bytes_current])\r\n\t, [Growth per day]=sum(database_growth_bytes_per_day)\r\n\tfrom [dbo].[vw_sqlwatch_report_dim_database] db\r\n\twhere db.sql_instance = s.sql_instance\r\n\tand db.database_name = DB_NAME()\r\n) dbs\r\n"
    }
   ]
  },
  {
   "title": "Disk Space Used %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for disk space\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nselect time=date_last_seen, disk=left([volume_name],2)+ '' '' + isnull(label,''''),1.0-[free_space_percentage]\nfrom [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_dim_os_volume] \nwhere sql_instance = ''$sql_instance''\norder by left([volume_name],2) asc'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "options": { "content": " " },
   "targets": [
    {}
   ]
  },
  {
   "title": "$sql_instance: SQL Server Blocking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "options": {
      "content": "# SQL Server Blocking Chains\r\n*****\r\nBlocking chains happen when one query is holding back other queries. This happens when poorly written query is holding excessive and exclusive locks on tables. Relational databases are written with ACID properties in mind, \r\nthis means that in order to retain data integrity, only one query at a time can modify the data. To achieve this, a lock is applied so no other queries can even read the data to avoid partially written data being displayed back to the client. When blocking chains happen for long period of time, you will have the impression that the database is slow, even though it isn't. It's just doing its job. It is important to undertand how locking works to avoid blocking chains.\r\n\r\nThese graphs come from data recorded in the Extended Events Session. For this to work, you must enable blocked process monitor: `sp_configure 'blocked process threshold', 5 ; -- set desired value in seconds`"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Blocking Sessions Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time = $__timeGroup(h.snapshot_time, $aggregation, previous)\r\n      ,[Blocking Session Count] = count(session_id)\r\n  FROM dbo.sqlwatch_logger_snapshot_header h\r\n  left join [dbo].[ufn_sqlwatch_get_blocking_chains] ($__timeFrom(), $__timeTo(),'$sql_instance') r1\r\n  on h.snapshot_time = r1.snapshot_time\r\n  and h.snapshot_type_id = r1.snapshot_type_id\r\n  and h.sql_instance = r1.sql_instance\r\n  and blocking_session_id is null -- header only  \r\n  where $__timeFilter(h.snapshot_time)\r\n  and h.snapshot_type_id = 9\r\n  group by $__timeGroup(h.snapshot_time, $aggregation, previous), convert(varchar(10),session_id)\r\n \r\n  order by time asc"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
     "options": {
      "content": "The Extended Events Session captures blocking chains according to the time set for the Blocking Process Monitor `select * from sys.configurations where name like 'blocked process threshold%`.\r\nFor example, if the monitor is set to 5 seconds and we have a blocking chain lasting 21 seconds, it will record it 4 times, every 5 seconds. All four occurences will be shown below."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Blocking Chains",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "rawSql": "select time=x.event_time, blocking_tree + ' (' + isnull(x.appname,'') + '; ' + isnull(x.hostname,'') + ') SQL: ' + isnull(x.sql_text,'') \nfrom [dbo].[ufn_sqlwatch_get_blocking_chains] ($__timeFrom(), $__timeTo(),'$sql_instance') x\n\norder by time"
      }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Requests and Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "options": {
      "content": "# SQL Server Requests\r\n*****\r\nList of current requests sampled from `dm_exec_requests`.\r\n\r\n**Runnable** - The session has been assigned a worker thread but it is waiting for CPU to become available.\r\nMany runnable threads would indicate CPU bottleneck.\r\n\r\n**Pending** - The session is awaiting a worker thread to be assigned. Unitil a workthread is assigned the session will not run even if the CPU is available.\r\nIn most cases, the worker will not be assigned due to CPU bottlenecks but in some cases, you may encounter a thread exhaustion.\r\nThis is a scenerio where SQL Server ran out of threads to allocate.\r\n\r\n**Suspended** - The session was running but has been put on hold due to lack of resources. Suspended session will likely have `wait_type` assigned to them.\r\n\r\n**Sleeping** - Sessions that SQL Server has put \"to sleep\" as they are not doing anything or could have ended recently but the connetion is still open. \r\nThis may be often observed with .NET Connection pooling. \r\n\r\nThis data provides a very high level view of the SQL Server Requests and Sessions. Becuase of the data sampling, we could be misssing a lot of the workload that happens between samples. However, this is by design, we do not want to capture too much of meaningless workload. Any transactions that cause trouble will be captured by Extended Events"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "User Requests by Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time = $__timeGroup(r1.snapshot_time, $aggregation,0)\r\n      ,  background\t= avg(background)\r\n      ,  running = avg(running)\t\r\n      ,  runnable = avg(runnable)\t\r\n      ,  sleeping\t = avg(sleeping)\r\n      ,  suspended\t = avg(suspended)\r\n      ,  waiting_tasks\t = avg(waiting_tasks)\r\n     -- ,  wait_duration_ms = avg(wait_duration_ms)\r\n      ,  type = case when type = 1 then 'User' else 'System' end\r\n  FROM [sqlwatch_logger_dm_exec_requests_stats] r1 (nolock)\r\n\twhere $__timeFilter(r1.snapshot_time)\r\n  and r1.sql_instance = '$sql_instance'\r\n  and type = 1\r\n  group by $__timeGroup(r1.snapshot_time, $aggregation,0), case when type = 1 then 'User' else 'System' end\r\n  order by time asc"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 74 },
     "options": {
      "content": "# SQL Server Sessions\r\n*****\r\nList of current sessions sampled from `dm_exec_sessions`.\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "User Sessions by Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time = $__timeGroup(r1.snapshot_time, $aggregation)\r\n      ,[running] = avg(running)\r\n      ,[sleeping] = avg(sleeping)\r\n      ,[dormant] = avg(dormant)\r\n      ,[preconnect] = avg(preconnect)\r\n      ,[cpu_time] = avg(cpu_time)\r\n      ,[reads] = avg(reads)\r\n      ,[writes] = avg(writes)\r\n      ,  type = case when type = 1 then 'User' else 'System' end\r\n  FROM [sqlwatch_logger_dm_exec_sessions_stats] r1 (nolock)\r\n\twhere $__timeFilter(r1.snapshot_time)\r\n  and r1.sql_instance = '$sql_instance'\r\n  and type = 1\r\n  group by $__timeGroup(r1.snapshot_time, $aggregation), case when type = 1 then 'User' else 'System' end\r\n  order by time asc"
      }
     ]
    },
    {
     "title": "User Sessions by Resource",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short", "label": "Active" }
     ],
     "targets": [
      { "panelId": 271 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "options": {
      "content": "# SQL Server Activity and Workload\r\n*****\r\n## CPU\r\nThe CPU chart is split into System (OS) and SQL Server. In an ideal scenario, all of the utilistaison should be allocated to SQL Server and only very small amount to system. SQL Server is also licensed per core, the more CPU cores the most expensive the license. You do not want to be paying a lot of money and not use it. [See Long Queries captured during this period](/d/sqlwatch-long-queries/long-queries?${__url_time_range}&var-DataSource=${DataSource}&var-sql_instance=${sql_instance})\r\nIf you are seeing a lot of OS Utilisation but not a lot of SQL Server utilistaion it means there is something else in the OS that uses CPU. It could be that you are running multiple SQL Instances?"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Processor Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation, previous)\n      ,[min] = min([cntr_value_calculated])\n      ,[max] = max([cntr_value_calculated])\n  FROM (\n    select snapshot_time, [cntr_value_calculated]=sum([cntr_value_calculated])\n    from [dbo].[sqlwatch_logger_perf_os_performance_counters] pc (readpast)\n\t\tinner join [dbo].[sqlwatch_meta_performance_counter] mpc  (readpast)\n\t\t\ton pc.sql_instance = mpc.sql_instance\n\t\t\tand pc.performance_counter_id = mpc.performance_counter_id      \n    WHERE $__timeFilter(pc.snapshot_time)\n  AND mpc.counter_name =  'Processor Time %' --case when serverproperty('EngineEdition') = 3 then 'CPU usage %' else 'Processor Time %' end\n  --and pc.instance_name NOT IN ('internal')\n  AND pc.[sql_instance] = '$sql_instance'    \n    group by snapshot_time\n  ) t\n  GROUP BY $__timeGroup([snapshot_time], $aggregation)\nORDER BY\n  time ASC\n\n  "
      },
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup(pc.[snapshot_time], $aggregation, previous)\n      ,metric = case when instance_name = 'system' then 'OS' else 'SQL Server' end\n      ,[value] = avg(pc.[cntr_value_calculated])\n  FROM [dbo].[sqlwatch_logger_perf_os_performance_counters] pc\n\t\tinner join [dbo].[sqlwatch_meta_performance_counter] mpc\n\t\t\ton pc.sql_instance = mpc.sql_instance\n\t\t\tand pc.performance_counter_id = mpc.performance_counter_id  \n  WHERE $__timeFilter(pc.snapshot_time)\n  AND mpc.counter_name IN ('Processor Time %')\n  and pc.instance_name IN ('sql','system')\n  AND pc.[sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup(pc.[snapshot_time], $aggregation) , case when instance_name = 'system' then 'OS' else 'SQL Server' end\nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
     "options": {
      "content": "# Captured Wait Events\r\nWait events longer than 1 second captured by extended events session.\r\n[See captured queries and transactions that have contributed to the wait](/d/sqlwatch-wait-events/wait-events?${__url_time_range}&var-DataSource=${DataSource}&var-sql_instance=${sql_instance})"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
     "options": {
      "content": "   \r\n\r\n## Activity  \r\n\r\n**Batch Requests/sec**: The number of batch requests received per second and is a good general indicator for the activity level of the SQL Server. This counter is highly dependent on the hardware and quality of code running on the server. The more powerful the hardware, the higher this number can be, even on poorly coded applications. A value of 1000 batch requests/sec is easily attainable, though a typical 100Mbs NIC can only handle about 3000 batch requests/sec. Many other counter thresholds depend upon batch requests/sec while, in some cases, a low (or high) number does not point to poor processing power. You should frequently use this counter in combination with other counters, such as processor utilization or user connections. In version 2000, \"Transactions/ sec\" was the counter most often used to measure overall activity, while versions 2005 and later use \"Batch Requests/sec\". Versions 2005 before SP2, measure this counter differently and may lead to some misunderstandings. Read the footnote for more details.\r\n\r\n**SQL Compilations/sec**: Number of times that Transact-SQL compilations occurred, per second (including recompiles). The lower this value is the better. High values often indicate excessive ad-hoc querying and should be as low as possible. If excessive ad-hoc querying is happening, try rewriting the queries as procedures or invoke the queries using sp_executeSQL. When rewriting isn’t possible, consider using a plan guide or setting the database to parameterization forced mode.\r\n\r\n**SQL Re-Compilations/sec**: The number of times, per second, that Transact-SQL objects attempted to be executed but had to be recompiled before completion. This number should be at or near zero since recompiles can cause deadlocks and exclusive compile locks. This counter’s value should follow in proportion to \"Batch Requests/sec\" and \"SQL Compilations/ sec\". This needs to be nil in your system as much as possible.\r\n\r\n**Logins/sec**: *You want < 2* The number of user logins per second. Any value over 2 may indicate insufficient connection pooling.\r\n\r\nUser Connections: The number of users currently connected to the SQL Server. This counter should roughly track with \"Batch Requests/Sec\". They should generally rise and fall together. For example, blocking problems could be revealed by rising user connections, lock waits and lock wait time coupled with declining batch requests/sec.\r\n\r\n**Transactions/sec**: Number of transactions started for the database per second."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select t.*\n\t  --rate calcs\n\t  ,[SQL Compilations Rate] = case when [Batch Requests/sec] > 0 then [SQL Compilations/sec] / [Batch Requests/sec] else 0 end\n\t  ,[SQL Re-Compilations Rate] = case when [SQL Compilations/sec] > 0 then [SQL Re-Compilations/sec]  / [SQL Compilations/sec] else 0 end\nfrom (\n  SELECT \n        [time] = $__timeGroup([snapshot_time], $aggregation) \n  \t\t  ,'SQL Compilations/sec' = AVG(case when counter_name = 'SQL Compilations/sec' then [cntr_value_calculated] else null end)\n  \t\t  ,'SQL Re-Compilations/sec' = AVG(case when counter_name = 'SQL Re-Compilations/sec' then [cntr_value_calculated] else null end)\n  \t\t  ,'Batch Requests/sec' = AVG(case when counter_name = 'Batch Requests/sec' then [cntr_value_calculated] else null end)\n  \t\t  ,'Logins/sec' = AVG(case when counter_name = 'Logins/sec' then [cntr_value_calculated] else null end)\n  \t\t  ,'Transactions/sec' = AVG(case when counter_name = 'Transactions/sec' then [cntr_value_calculated] else null end)\n  \t\t  ,'User Connections' = AVG(case when counter_name = 'User Connections' then [cntr_value_calculated] else null end)\n    FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n    WHERE [aggregation_interval_minutes] = 0\n    AND $__timeFilter(snapshot_time)\n    AND counter_name IN (\n  \t\t'SQL Compilations/sec'\n  \t\t,'SQL Re-Compilations/sec'\n  \t\t,'Batch Requests/sec'\n  \t\t,'Logins/sec'\n  \t\t,'Transactions/sec'\n  \t\t,'User Connections'\n  \t\t,'SQL Compilations/sec'\n  \t\t,'SQL Re-Compilations/sec')\n    AND [sql_instance] = '$sql_instance'\n    GROUP BY $__timeGroup([snapshot_time], $aggregation)\n  ) t\nORDER BY\n  time ASC\noption (keep plan)"
      }
     ]
    },
    {
     "title": "Database Transactions /sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Transactions/sec')\n  AND instance_name IN ($database)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  option (keep plan)\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
     "options": {
      "content": "<br><br><h2 id=\"compilations\">SQL Compilations</h2>\r\n\r\n<p><b>SQL Compilations/sec</b>:  You want it to be < 10% (of the number of Batch Requests/Sec). Number of times that Transact-SQL compilations occurred, per second (including recompiles). The lower this value is the better. High values often indicate excessive ad-hoc querying and should be as low as possible. If excessive ad-hoc querying is happening, try rewriting the queries as procedures or invoke the queries using sp_executeSQL. When rewriting isn’t possible, consider using a plan guide or setting the database to parameterization forced mode.</p>\r\n\r\n<p><b>SQL Re-Compilations/sec</b>: You want it to be < 10% (of the number of SQL Compilations/sec). The number of times, per second, that Transact-SQL objects attempted to be executed but had to be recompiled before completion. This number should be at or near zero since recompiles can cause deadlocks and exclusive compile locks. This counter’s value should follow in proportion to \"Batch Requests/sec\" and \"SQL Compilations/ sec\". This needs to be nil in your system as much as possible.</p>\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Compilation Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "panelId": 231 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Waits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "options": {
      "content": "# Wait Times\r\n\r\nIf a particular resource is not available, SQL Server will have to wait before it can process the query. For example, if the storage is too slow, SQL Server will have to wait for the disk \"to deliver\" the data. Analogically, if the CPU is too busy, SQL Server will have to wait for it to become available.\r\nAll this means, that if SQL is waiting too much, our queries do not get executed straight away but are put in a queue which makes the system feel slow. This chart is critical in understanding what SQL Server is waiting on. The SQLSkills website is a great resource to learn about waits:\r\n[https://www.sqlskills.com/help/waits/](https://www.sqlskills.com/help/waits/). You can change how the wait types are grouped, either by Type or Category, using the filter on top or link in the chart."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Wait Time $WaitCalc by Wait $Waits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,[value] = case when '$WaitCalc' = 'ms/sec' then avg([wait_time_ms_per_second]) else avg(wait_time_ms_delta) end\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_wait_stats]\n  WHERE 1=1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  option (keep plan)\n  "
      }
     ]
    },
    {
     "title": "Wait Events",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time]= event_time\n      ,[Wait Type] = case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,[Wait Duration] = sum([duration])\n  FROM [vw_sqlwatch_report_fact_xes_wait_events]\n    \n  WHERE $__timeFilter(event_time)\n  AND [sql_instance] = '$sql_instance'\n\n  group by event_time,case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\nORDER BY\n  time ASC\n  option (keep plan)"
      }
     ]
    },
    {
     "title": "Queries",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "rawSql": "select \t event_time\t\n\t,wait_type\t\n\t,wait_category\t\n\t--,activity_id = convert(varchar(36),activity_id)\t\n\t--,activity_id_sequence\t\n\t,duration\t\n\t---,signal_duration\t\n\t,session_id\t\n\t,username\t\n\t,client_hostname\t\n\t,client_app_name\t\n\t,database_name\t\n\t--,sql_instance\t\n\t--,snapshot_time\t\n\t--,snapshot_type_id\n\t--,sqlwatch_query_hash = '--0x'+convert(varchar(max),sqlwatch_query_hash,2)\nfrom [dbo].[vw_sqlwatch_report_fact_xes_wait_events] \nWHERE [sql_instance] = '$sql_instance'\nAND $__timeFilter(event_time)"
      }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Query Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "options": {
      "content": "<br><br><h2 id=\"scheduler\">Scheduler Tasks</h2>\r\n<p>SQL Server has its own, internal task mechanism controlled by the SQLOS. Every time we run a query, SQL Server will invoke one or more tasks to run this task, get data from tables etc. SQL Server has one scheduler per CPU thread. <a href=\"https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-schedulers-transact-sql\">More details.</a><br>\r\n<b>Runnable Tasks:</b> You want 0. Number of workers, with tasks assigned to them, that are waiting to be scheduled on the runnable queue. If this number is high, it may indicate CPU pressure.<br>\r\n<b>Pending Disk IO:</b> You want 0. Number of pending I/Os that are waiting to be completed.<br>\r\n<b>Failed To Create Worker: </b> You want 0. Inability to create new work generally occurs because of memory constraints.<br>\r\n<b>Tasks Queue:</b> You want 0. Shows number of tasks awaiting a worker to pick them up.<br>\r\n<b>Current Tasks:</b> Number of tasks assigned to a scheduler. Task can be actively running or waiting.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Scheduler Tasks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation, previous) \n      ,[Runnable Tasks] = AVG([runnable_tasks_count])\n      ,[Pending Disk IO] = AVG(pending_disk_io_count)\n      ,[Failed To Create Worker] = AVG(failed_to_create_worker)\n      ,[Tasks Queue] = AVG(work_queue_count)\n      ,[Current Tasks] = avg(current_tasks_count)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_schedulers]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation, previous) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Query Processing",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time= $__timeGroup([snapshot_time], $aggregation, previous) \r\n      ,[max_workers]=MAX([max_workers])\r\n      ,[workers_created]=AVG([workers_created])\r\n      ,[idle_workers]=AVG([idle_workers])\r\n      ,[pending_tasks]=AVG([pending_tasks])\r\n  FROM [dbo].[sqlwatch_logger_xes_query_processing]\r\n   WHERE $__timeFilter(snapshot_time)\r\n  AND [sql_instance] = '$sql_instance'\r\n  GROUP BY $__timeGroup([snapshot_time], $aggregation, previous) \r\nORDER BY\r\n  time ASC"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "options": {
      "content": "<p>\r\n<b>Auto-Param Attempts/sec</b> Number of auto-parameterization attempts per second. Total should be the sum of the failed, safe, and unsafe auto-parameterizations. Auto-parameterization occurs when an instance of SQL Server tries to parameterize a Transact-SQL request by replacing some literals with parameters so that reuse of the resulting cached execution plan across multiple similar-looking requests is possible. Note that auto-parameterizations are also known as simple parameterizations in newer versions of SQL Server. This counter does not include forced parameterizations.\r\n<br>\r\n<b>Failed Auto-Params/sec</b> \tNumber of failed auto-parameterization attempts per second. This should be small. Note that auto-parameterizations are also known as simple parameterizations in later versions of SQL Server.\r\n<br>\r\n<b>Forced Parameterizations/sec</b> Number of successful forced parameterizations per second.\r\n<br>\r\n<b>Safe Auto-Params/sec</b> Number of safe auto-parameterization attempts per second. Safe refers to a determination that a cached execution plan can be shared between different similar-looking Transact-SQL statements. SQL Server makes many auto-parameterization attempts some of which turn out to be safe and others fail. Note that auto-parameterizations are also known as simple parameterizations in later versions of SQL Server. This does not include forced parameterizations.\r\n<br>\r\n<b>Unsafe Auto-Params/sec</b> Number of unsafe auto-parameterization attempts per second. For example, the query has some characteristics that prevent the cached plan from being shared. These are designated as unsafe. This does not count the number of forced parameterizations.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Parametrization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,'Auto-Param Attempts/sec' = avg(case when [counter_name] = 'Auto-Param Attempts/sec' then [cntr_value_calculated] else null end)\n      ,'Failed Auto-Params/sec' = avg(case when [counter_name] = 'Failed Auto-Params/sec' then [cntr_value_calculated] else null end)\n      ,'Forced Parameterizations/sec' = avg(case when [counter_name] = 'Forced Parameterizations/sec' then [cntr_value_calculated] else null end)\n      ,'Safe Auto-Params/sec' = avg(case when [counter_name] = 'Safe Auto-Params/sec' then [cntr_value_calculated] else null end)\n      ,'Unsafe Auto-Params/sec' = avg(case when [counter_name] = 'Unsafe Auto-Params/sec' then [cntr_value_calculated] else null end)\n      ,'Errors/sec' = avg(case when [counter_name] = 'Errors/sec' and [instance_name] not in ('User Errors','Info Errors','_Total') then [cntr_value_calculated] else null end)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Auto-Param Attempts/sec','Failed Auto-Params/sec','Forced Parameterizations/sec','Safe Auto-Params/sec','Unsafe Auto-Params/sec'\n    ,'Errors/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation)\nORDER BY\n  time ASC"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 68 },
     "options": {
      "content": "<br><br><h2 id=\"long\">Long Queries</h2>\r\n<p>Long running queries are usually caused by poor queries, trying to process too much data at a time clogging CPU, Memory and oversaturating storage. However, some long running processes are OK, for example sleeping tasks or background processes that do not eaty too much resources.\r\nIf you have a long running query that you are OK with, you can exclude it from collection in <span style=\"font-family:monospace;font-size:12px;background:#3D3D3D;padding:2px 4px 2px 4px;border-radius:2px;\">[dbo].[sqlwatch_config_exclude_xes_long_query]</span></p>\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Long Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT [time] = h.snapshot_time\r\n      , [Long Sessions]=count(distinct [session_id])\r\n \r\n  FROM [dbo].[sqlwatch_logger_snapshot_header] h --this is so we always get row to show the tile, even if there are no rows in the data view. otherwise the tile will not be shown\r\n  left join [dbo].[vw_sqlwatch_report_fact_xes_long_queries] l\r\n    on h.sql_instance = l.sql_instance\r\n    and h.snapshot_time = l.snapshot_time\r\n    and h.snapshot_type_id = l.snapshot_type_id\r\n  where h.[sql_instance] = '$sql_instance'\r\n   AND $__timeFilter(h.snapshot_time)\r\n   group by h.snapshot_time\r\nORDER BY\r\n  time desc"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 78 },
     "options": {
      "content": "<br><br><h2 id=\"errors\">Errors</h2>\r\n<p>Errors reported by SQL engine, excludes \"User Errors\" and \"Info Errors\". These will likely be relatively serious, such a broken connections, kill connections, database offline errors.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Errors/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 209 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Locking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "options": {
      "content": "<br><h1 id=\"locking\">SQL Server Locking</h1>\r\n<p>Locking mechanism is critical part of every relational database. Every time a row is read, inserted or modified SQL Server applies appropriate locks to ensure no one else can access the data whilst it's being read of modified. The locking mechanism ensures data consistency however, excessive locking can lead overal poor performance and even create blocking chains.</p>\r\n<br>\r\n<p><b>Lock Requests / sec</b>: *You want <1000*.  The number of new locks and locks converted per second. This metric’s value should generally correspond to \"Batch Requests/sec\". Values > 1000 may indicate queries are accessing very large numbers of rows and may benefit from tuning.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Lock Requests/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,'Lock Requests/sec' = avg(case when [counter_name] = 'Lock Requests/sec' then [cntr_value_calculated] else null end)\n      ,'Batch Requests/sec' = avg(case when [counter_name] = 'Batch Requests/sec' then [cntr_value_calculated] else null end)\n      ,'Lock Timeouts/sec' = avg(case when [counter_name] = 'Lock Timeouts/sec' then [cntr_value_calculated] else null end)\n      ,'Lock Waits/sec' = avg(case when [counter_name] = 'Lock Waits/sec' then [cntr_value_calculated] else null end)\n      ,'Average Wait Time (ms)' = avg(case when [counter_name] = 'Average Wait Time (ms)' then [cntr_value_calculated] else null end)\n      ,'Processes blocked' = sum(case when [counter_name] = 'Processes blocked' then [cntr_value_calculated] else null end)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Lock Requests/sec','Batch Requests/sec','Lock Timeouts/sec','Lock Waits/sec','Average Wait Time (ms)','Processes blocked')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
     "options": {
      "content": "<br><p><b>Lock Timeouts/ sec</b>: *You want <1*.  Shows the number of lock requests per second that timed out, including internal requests for NOWAIT locks. A value greater than zero might indicate that user queries are not completing. The lower this value is, the better.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Lock Timeouts/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 79 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
     "options": {
      "content": "<br>\r\n<p><b>Lock Waits/sec</b>: *You want 0*.  How many times users waited to acquire a lock over the past second. Values greater than zero indicate at least some blocking is occurring, while a value of zero can quickly eliminate blocking as a potential root-cause problem. As with \"Lock Wait Time\", lock waits are not recorded by PerfMon until after the lock event completes.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Lock Waits/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 79 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 67 },
     "options": {
      "content": "<br>\r\n<p>\r\n<b>Avg Wait Time (ms)</b>: *You want <500 *   \r\nThe average wait time, in milliseconds, for each lock request that had to wait. Average wait time longer than 500ms may indicate excessive blocking. This value should generally correlate to \"Lock Waits/sec\" and move up or down with it accordingly.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Average Wait Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "panelId": 79 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 76 },
     "options": {
      "content": "<br>\r\n<p><b>Blocking chains</b> Excessive locking can cause blocking chains. Blocking chains happen when two or more queries are trying to access data that is being locked by the first query. In such case, none of the queries can complete until the first query completes first. Blocking chains often indicate bad indexes, excessive scanning, lock escanation and overall bad application design.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Blocked Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 79 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 39 },
     "options": {
      "content": "<br><h1 id=\"memory\">SQL Server Memory</h2>\r\n<p>The memory section shows the internals of SQL Server memory and its pressure points.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Physical memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Physical Memory in use] = AVG([physical_memory_in_use_kb])\n      ,[Available Commit limit] = AVG(available_commit_limit_kb)\n      ,[Physical Memory Low Indicator] = MAX(convert(int,process_physical_memory_low))\n      ,[Virtual Memory Low Indicator] = MAX(convert(int,process_virtual_memory_low))\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_process_memory]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "SQL Memory Breakdown",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      --this chart\n      ,'Connection Memory (KB)' = avg(case when counter_name = 'Connection Memory (KB)' then [cntr_value_calculated] else null end)\n      ,'Optimizer Memory (KB)' = avg(case when counter_name = 'Optimizer Memory (KB)' then [cntr_value_calculated] else null end)\n      ,'SQL Cache Memory (KB)' = avg(case when counter_name = 'SQL Cache Memory (KB)' then [cntr_value_calculated] else null end)\n      --other charts\n      ,'Total Server Memory (KB)' = avg(case when counter_name = 'Total Server Memory (KB)' then [cntr_value_calculated] else null end)\n      ,'Stolen Server Memory (KB)' = avg(case when counter_name = 'Stolen Server Memory (KB)' then [cntr_value_calculated] else null end)\n      ,'Target Server Memory (KB)' = avg(case when counter_name = 'Target Server Memory (KB)' then [cntr_value_calculated] else null end)\n      --\n      ,'Memory Grants Outstanding' = avg(case when counter_name = 'Memory Grants Outstanding' then [cntr_value_calculated] else null end)\n      ,'Memory Grants Pending' = avg(case when counter_name = 'Memory Grants Pending' then [cntr_value_calculated] else null end)\n      --\n      ,'Free list stalls/sec' = avg(case when counter_name = 'Free list stalls/sec' then [cntr_value_calculated] else null end)\n      --\n      ,'Page Lookups/sec' = avg(case when counter_name = 'Page Lookups/sec' then [cntr_value_calculated] else null end)\n      ,'Batch Requests/sec' = avg(case when counter_name = 'Batch Requests/sec' then [cntr_value_calculated] else null end)\n      --\n      ,'Page reads/sec' = avg(case when counter_name = 'Page reads/sec' then [cntr_value_calculated] else null end)\n      ,'Page writes/sec' = avg(case when counter_name = 'Page writes/sec' then [cntr_value_calculated] else null end)\n      --\n      ,'Readahead pages/sec' = avg(case when counter_name = 'Readahead pages/sec' then [cntr_value_calculated] else null end)\n      --\n      ,'Checkpoint pages/sec' = avg(case when counter_name = 'Checkpoint pages/sec' then [cntr_value_calculated] else null end)\n      --\n      ,'Lazy writes/sec' = avg(case when counter_name = 'Lazy writes/sec' then [cntr_value_calculated] else null end)\n      --\n      ,'Page life Expectancy'  = avg(case when counter_name = 'Page life Expectancy' then [cntr_value_calculated] else null end)\n      --\n      ,'Buffer cache hit ratio'  = avg(case when counter_name = 'Buffer cache hit ratio' then [cntr_value_calculated] else null end)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Connection Memory (KB)','Optimizer Memory (KB)','SQL Cache Memory (KB)'\n                      ,'Total Server Memory (KB)','Stolen Server Memory (KB)', 'Target Server Memory (KB)'\n                      ,'Memory Grants Outstanding','Memory Grants Pending'\n                      ,'Free list stalls/sec'\n                      ,'Page Lookups/sec','Batch Requests/sec'\n                      ,'Page reads/sec','Page writes/sec'\n                      ,'Readahead pages/sec','Page reads/sec'\n                      ,'Checkpoint pages/sec'\n                      ,'Lazy writes/sec'\n                      ,'Page life Expectancy'\n                      ,'Buffer cache hit ratio'\n                      )\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "title": "Memory Clerks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [clerk_name]\n      ,[value] = sum([allocated_kb])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_memory_clerks]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [clerk_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 71 },
     "options": {
      "content": "<br>\r\n<p><b>Memory Grants Outstanding</b>: The total number of processes per second that have successfully acquired a workspace memory grant.<br>\r\n<b>Memory Grants Pending </b>: *You want 0*  The total number of processes per second waiting for a workspace memory grant. Numbers higher than 0 indicate a lack of memory.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Memory Grants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
     "options": {
      "content": "<br>\r\n<p>\r\n<b>Free List Stalls/sec</b>: *You want < 2*. Monitors the number of requests per second where data requests stall because no buffers are available. Any value above 2 means SQL Server needs more memory.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Free list stalls/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 },
     "options": {
      "content": "<br>\r\n<p><b>Page lookups Rate</b>: *You want < 100*  The ratio of *Page lookups/ sec* and *Batch Requests/ sec*. The number of requests to find a page in the buffer pool. When the ratio of batch requests to page lookups crests 100, you may have inefficient execution plans or too many adhoc queries.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Page Lookup Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 96 },
     "options": {
      "content": "<br>\r\n<p>\r\n<b>\r\nPage Reads/sec\r\n</b>:   *You want < 90* The number of physical database page reads issued per second. Normal OLTP workloads support 80 – 90 per second, but higher values may be a yellow flag for poor indexing or insufficient memory.\r\n</p>\r\n\r\n\r\n<p>\r\n<b>Page Writes/sec</b>: *You want < 90* The number of database pages physically written to disk per second. Normal OLTP workloads support 80 – 90 per second. Values over 90 should be crossed checked with \"lazy writer/sec\" and \"checkpoint\" counters. If the other counters are also high, then it may indicate insufficient memory.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Page reads/sec vs Page writes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 106 },
     "options": {
      "content": "<br>\r\n<p>\r\n<b>Readahead/sec</b>:  *You want < 20% of Page Reads/ sec*   \r\nThe number of data pages read per second in anticipation of their use. If this value is made up even a sizeable minority of total Page Reads/sec (say, greater than 20% of total page reads), you may have too many physical reads occurring.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Readahead pages/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 114 },
     "options": {
      "content": "**Checkpoint Pages/ sec**: Monitors the number of dirty pages, per second, that are flushed to disk when SQL Server invokes the checkpoint process. Checkpoint frequency is influenced by the recovery interval setting in sp_configure. High values for this counter may indicate insufficient memory or that the recovery interval is too high."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Checkpoint pages/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 122 },
     "options": {
      "content": "<br>\r\n<p><b>Lazy Writes/Sec</b>: *You want< 20*   \r\nMonitors the number of times per second that the Lazy Writer process moves dirty pages from the buffer to disk as it frees up buffer space. Lower is better with zero being ideal. When greater than 20, this counter indicates a need for more memory.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Lazy writes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 130 },
     "options": {
      "content": "<br>\r\n<p><b>Page Life Expectancy</b> Tells, on average, how many seconds SQL Server expects a data page to stay in cache. The target on an OLTP system should be at least 300 (5 min). When under 300, this may indicate poor index design (leading to increased disk I/O and less effective use of memory) or, simply, a potential shortage of memory. </p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Avg page life expentancy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 139 },
     "options": {
      "content": "<br>\r\n<p><b>Buffer Cache Hit Ratio</b> Long a stalwart counter used by SQL Server DBAs, this counter is no longer very useful. It monitors the percentage of data requests answer from the buffer cache since the last reboot. However, other counters are much better for showing current memory pressure that this one because it blows the curve. For example, PLE (page life expectancy) might suddenly drop from 2000 to 70, while buffer cache hit ration moves only from 98.2 to 98.1. Only be concerned by this counter if it’s value is regularly below 90 (for OLTP) or 80 (for very large OLAP).\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Buffer cache hit ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      { "panelId": 34 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server TempDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
     "options": {
      "content": "<br><h1 id=\"tempdb\">TempDB</h1>\r\n<p>TempDB is a temporary, and very important database in SQL Server. We, users, can use it by creating temporary tables #table or ##table or even physical tables dbo.table. The tempdb is recreated every time SQL Server starts so we must not be storing anything of value there.\r\nSQL Server heavily relies on tempodb for its query execution - sometime it will use tempdb for sorting data or to \"spill\" data if it runs out of memory or if the query is not optimised. So, when we say \"my query does not use tempdb\" this may not be true.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Active Temp Tables",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,'Active Temp Tables' = avg(case when counter_name = 'Active Temp Tables' then cntr_value_calculated else null end)\n      ,'Temp Tables Creation Rate' = avg(case when counter_name = 'Temp Tables Creation Rate' then cntr_value_calculated else null end)\n      ,'Free Space in tempdb (KB)' = avg(case when counter_name = 'Free Space in tempdb (KB)' then cntr_value_calculated else null end)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Active Temp Tables','Temp Tables Creation Rate','Free Space in tempdb (KB)')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Temp Tables Creation Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 72 }
     ]
    },
    {
     "title": "Free space in tempdb",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      { "panelId": 72 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "options": {
      "content": "<br><h1 id=\"storage\">SQL Server Storage</h1>\r\n<p>SQL Server is very fast at handling large volumes of data per CPU core. However, that data has to come from the storage so it is critical that the storage is able to deliver the desired throughput.<br>\r\nYou will want to make sure that the storage interfaces are not saturated and if they are, you will have to look at either upgrading or performance tunning your storage devices. Or, tune your queries to pull less data.</p>\r\n<p>This section shows what SQL Server does with the storage, how much data its reading or writing, how it uses indexes etc...</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Bytes Transferred",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n        [time] = $__timeGroup([snapshot_time], $aggregation) \n      , [Bytes Written] = SUM([num_of_bytes_written_delta])\n      , [Bytes Read] = SUM([num_of_bytes_read_delta])\n      , [Bytes Written/sec] = AVG([bytes_written_per_second])\n      , [Bytes Read/sec] = AVG([bytes_read_per_second])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  AND database_name IN ($database)\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Bytes written/sec vs Bytes read/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      { "panelId": 14 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
     "options": {
      "content": "<br><p><b>Page Splits/sec</b> :  *You want < 20 per 100 Batch Requests/Sec* - Monitors the number of page splits per second which occur due to overflowing index pages and should be as low as possible. To avoid page splits, review table and index design to reduce non-sequential inserts or implement fill factor and pad_index to leave more empty space per page. NOTE: A high value for this counter is not bad in situations where many new pages are being created since it includes new page allocations.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Page Splits/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Page Splits/sec','Batch Requests/Sec','Log write waits','Log Flushes/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Long IO requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Latency] = SUM([total_long_ios])\n      ,metric=ISNULL([longest_pending_request_file],'')\n  FROM [dbo].[vw_sqlwatch_report_fact_xes_iosubsystem]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) ,[longest_pending_request_file]\nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Log write waits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 91 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 21, "x": 0, "y": 79 },
     "options": {
      "content": "<br>\r\n<p>\r\n<b>Log Flushes/sec</b>: Technically, the number of log pages flushed to the transaction log per second.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Log Flushes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 91 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 },
     "options": {
      "content": "<p>Making the file physically bigger is an expensive operation for the operating system. If you have a lot of log grows you may consider \"pre-growing\" files manually to a set size.<br>\r\nIn modern OS, you can also look at enablig Instant File Initialization which can grow files at no cost.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Log Growths",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = SUM([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Log Growths')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 95 },
     "options": {
      "content": "<br>\r\n<p><b>Full Scans/sec</b>: *You want 1 Full Scan/sec per 1000 Index Searches/sec*. Monitors the number of full scans on tables or indexes. Ignore unless high CPU coincides with high scan rates. High scan rates may be caused by missing indexes, very small tables, or requests for too many records. A sudden increase in this value may indicate a statistics threshold has been reached, resulting in an index no longer being used.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Full Scans /sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Full Scans/sec','Index Searches/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Long Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
     "options": {
      "content": "# Long Queries\r\n\r\nLong queries are captured by the extended event session.\r\nBy default, any query runnig for longer than 5 seconds will be loogged.\r\nYou may want to tweak the the session to exclude certain queries or increase the duration."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Long Queries",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time=$__timeGroup(event_time,$aggregation, 0),\n      [Long Queries] = count(*)\nFROM [dbo].[sqlwatch_logger_xes_long_queries]\nWHERE $__timeFilter([event_time])\nand sql_instance = '$sql_instance'\nGROUP BY $__timeGroup(event_time,$aggregation, 0)\n"
      }
     ]
    },
    {
     "title": "Long Queries",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT       event_time\n      ,[event_name]\n      ,[session_id]\n      ,[database_name]\n      ,[cpu_time]\n      ,[physical_reads]\n      ,[logical_reads]\n      ,[writes]\n      ,[spills]\n     ,[username]\n    ,[client_hostname]\n      ,[client_app_name]\n      ,[duration_ms]\n      ,[long_query_id]\n    , sql_text      \nFROM [dbo].[vw_sqlwatch_report_fact_xes_long_queries]\nWHERE $__timeFilter([event_time])\nand sql_instance = '$sql_instance'"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
     "options": {
      "content": "<br><a href=\"/d/sqlwatch-repository-summary/repository-dashboard?orgId=1&refresh=15s\">Repository Dashboard</a>\r\n<p>Folded panels become inactive and do not query database.</p>"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: OS Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
     "options": {
      "content": "<br><h1 id=\"disks\">OS Disks</h1>\r\n<p>In OLTP systems the ideal latency is below 8ms but anything below 20ms can be acceptable. The latency between 20ms and 50ms could lead to performance problems. Latency above 50ms is likely inadequate if you want a fast database. In the Data Warehouse workload, latencies around 500ms and more are not uncommon. This is becuase in the Data Warehouse we are often reading a lot of data at once and saturate the storage IO whereas in OLTP systems we are making a lot of small writes and reads and therefore storage must be very responsive.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Logical disk latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Latency] = MAX([io_latency_read])+MAX([io_latency_write])\n      ,metric=left([file_physical_name],1)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) , left([file_physical_name],1)\nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Physical File Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,'Read Latency' = MAX([io_latency_read])\n      ,'Write Latency' = MAX([io_latency_write])\n      ,'Bytes Read Delta' = SUM([num_of_bytes_read_delta])\n      ,'Bytes Written Delta' = SUM([num_of_bytes_written_delta])\n      ,metric=file_physical_name\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n   AND database_name IN ($database)\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) , file_physical_name\nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Physical File Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "panelId": 61 }
     ]
    },
    {
     "title": "Physical File Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "panelId": 61 }
     ]
    },
    {
     "title": "Physical File Writes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "panelId": 61 }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: OS Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
     "options": {
      "content": "<br><h1 id=\"network\">OS Network</h1>\r\n<p>Network interfaces exposed to the OS. Any network traffic from and to SQL Server will be going through these.</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Network IO waits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name = 'Network IO waits'\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: Availability Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 45 },
     "options": {
      "content": "<br><h1 id=\"network\">Availability Group Replicas</h1>\r\n<p><a href=\"https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-database-replica\">More details about AG related perf counters</a>\r\n</p>\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Current Replica States",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "rawSql": "select [hadr_group_name]\r\n      ,[replica_server_name]\r\n      ,[availability_mode_desc]\r\n      ,[failover_mode_desc]\r\n      ,[database_name]\r\n      ,[is_local]\r\n      ,[is_primary_replica]\r\n      ,[synchronization_state_desc]\r\n      ,[is_commit_participant]\r\n      ,[synchronization_health_desc]\r\n\t  ,[database_state]\r\n      ,[database_state_desc]\r\n      ,[is_suspended]\r\n      ,[suspend_reason_desc]\r\n      ,[log_send_queue_size]\r\n      ,[log_send_rate]\r\n      ,[redo_queue_size]\r\n      ,[redo_rate]\r\n      ,[filestream_send_rate]\r\n      ,[secondary_lag_seconds]\r\n      ,[last_commit_time]\r\n      ,[snapshot_time]\r\n      ,[sql_instance]\r\nfrom (\r\n\tSELECT *\r\n\t\r\n\t, RN=ROW_NUMBER() over (partition by hadr_group_name, replica_server_name, database_name, sql_instance order by snapshot_time desc)\r\n\t  FROM [dbo].[vw_sqlwatch_report_hadr_database_replica_states]\r\n\t  WHERE $__timeFilter(snapshot_time)\r\n\t  AND sql_instance = '$sql_instance'\r\n\t  ) t\r\nWHERE RN=1"
      }
     ]
    },
    {
     "title": "Redo rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name in ('Redone Bytes/sec')\n  AND [sql_instance] = '$sql_instance'\n\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Bytes Sent to Replica",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name in ('Bytes Sent to Replica/sec')\n  AND [sql_instance] = '$sql_instance'\n\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "title": "Bytes Received from Replica",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name in ('Bytes Received from Replica/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 },
     "options": {
      "content": "<br>\r\n<p>\r\n\r\n<b>Log Send Queue</b> Amount of log records in the log files of the primary database, in kilobytes, that haven't been sent to the secondary replica. This value is sent to the secondary replica from the primary replica. Queue size doesn't include FILESTREAM files that are sent to a secondary.\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Log Send Queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 0\n  AND $__timeFilter(snapshot_time)\n  AND counter_name in ('Log Send Queue')\n  AND [sql_instance] = '$sql_instance'\n\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
      }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Check Failure History",
     "type": "graph",
     "description": "0 - OK\n1 - WARNING\n2 - CRITICAL\n3 - CHECK ERROR",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT  [metric] = replace([check_name],' failure count','')\n        ,value = CASE [check_status] \n        WHEN 'CRITICAL' THEN 2\n        WHEN 'WARNING' THEN 1\n        WHEN 'OK' THEN 0\n        ELSE 3 END\n        ,time=[snapshot_time]\n  FROM [dbo].[vw_sqlwatch_report_fact_check] with (nolock)\n  WHERE  target_sql_instance = '$sql_instance'\n  --AND check_enabled = 1\n  AND $__timeFilter([snapshot_time])\n  AND check_status <> 'OK'\n  --AND last_check_status IN ($Status)\n  order by time asc"
      }
     ]
    },
    {
     "title": "Checks",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "rawSql": "SELECT  [check_name] = replace([check_name],' failure count','')\n        , check_description\n        ,[last_check_value] = convert(varchar(max),[last_check_value])\n        ,status = CASE [last_check_status] \n        WHEN 'CRITICAL' THEN 2\n        WHEN 'WARNING' THEN 1\n        WHEN 'OK' THEN 0\n        ELSE 3 END\n        ,last_check_date\n  FROM [dbo].[vw_sqlwatch_report_dim_check] with (nolock)\n  WHERE  [target_sql_instance] = '$sql_instance'\n  AND check_enabled = 1\n  --AND $__timeFilter(last_check_date)\n  --AND last_check_status IN ($Status)\n  order by case when last_check_status = 'OK' then dateadd(month,-1,last_check_date) else last_check_date end desc"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 68 },
     "options": {
      "content": "# Checks Execution Time\nChecks execution time tells us how it takes to execute each check.\nThis is important as the check execution is single threaded and runs every minute. All checks must complete within that minute.\nIf you are writing custom checks you must make sure that they complete within milliseconds."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Check Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time=$__timeGroup(snapshot_time, $aggregation)\r\n      ,metric='(' + convert(varchar(10),[check_id]) + ') ' + [check_name] \r\n      ,[value]=avg([check_exec_time_ms])\r\n  FROM [dbo].[vw_sqlwatch_report_fact_check] with (nolock)\r\n  WHERE  target_sql_instance = '$sql_instance'\r\n  --AND check_enabled = 1\r\n  AND $__timeFilter([snapshot_time])\r\n  AND check_status <> 'OK'\r\n  --AND last_check_status IN ($Status)\r\n  group by $__timeGroup(snapshot_time, $aggregation), '(' + convert(varchar(10),[check_id]) + ') ' + [check_name] \r\n  order by time asc"
      }
     ]
    }
   ]
  },
  {
   "title": "$sql_instance: SQL Server Overview - Alternative Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
     "options": {
      "content": " ## Altenarnative charts for the Overview panel\r\n Some data is best presented as timeline and some as bar chart.\r\n Bar charts provide a way of comparison across metrics so we can see which ones stand our but sparklines provide a bit of history os we can see how the metric was doing in the last few minutes. However, sparklines do not provide any comparison across metrics.\r\n I am giving you an option to pick whichever module you want, just drag and drop and delete those you do not need.\r\n The beauty of Grafana is that you can build your own dashboards!"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Sessions",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 6, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time = r1.snapshot_time\r\n      ,[running] = avg(running)\r\n      ,[sleeping] = avg(sleeping)\r\n      ,[dormant] = avg(dormant)\r\n      --,[preconnect] = avg(preconnect)\r\n      ,[cpu_time] = avg(cpu_time)\r\n      ,[reads] = avg(reads)\r\n      ,[writes] = avg(writes)\r\n      ,  type = case when type = 1 then 'User' else 'System' end\r\n  FROM [sqlwatch_logger_dm_exec_sessions_stats] r1 (nolock)\r\n\twhere $__timeFilter(r1.snapshot_time)\r\n  and snapshot_time > dateadd(minute,-15,GETUTCDATE())\t\r\n  and r1.sql_instance = '$sql_instance'\r\n  group by r1.snapshot_time, case when type = 1 then 'User' else 'System' end\r\n  order by time asc"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 12, "w": 3, "x": 9, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time = r1.snapshot_time\r\n      ,  Background\t= background\r\n      ,  Running = running\r\n      ,  Runnable = runnable\r\n      ,  Sleeping\t = sleeping\r\n      ,  Suspended\t = suspended\r\n      ,  Waiting\t = waiting_tasks\r\n  FROM [sqlwatch_logger_dm_exec_requests_stats] r1 (nolock)\r\n\twhere $__timeFilter(r1.snapshot_time)\r\n\tand r1.snapshot_time > dateadd(minute,-15,getutcdate())\r\n  and r1.sql_instance = '$sql_instance'\r\n  and type = 1\r\n  order by time asc"
      }
     ]
    },
    {
     "title": "SQL Memory",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 3, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 269 }
     ]
    },
    {
     "title": "Disk IO",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 3, "x": 15, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 15 }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 3, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n      [time] = snapshot_time \n      ,[Latency Reads] = MAX(fs.[io_latency_read])\n      ,[Latency Writes] = MAX(fs.[io_latency_write])\n  \t  ,[Reads IO] = AVG(fs.bytes_read_per_second)\n  \t  ,[Writes IO] = AVG(fs.bytes_written_per_second)\n      ,[Disk] = left(upper([file_physical_name]),2) + ' ' + isnull(v.label,'')\n      ,[Max Latency] = max(case when fs.[io_latency_read] > fs.[io_latency_write] then fs.[io_latency_read] else fs.[io_latency_write] end)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats] fs\n  outer apply (\n    select top 1 label \n    from [dbo].[sqlwatch_meta_os_volume] v\n\t  where v.volume_name = left(fs.file_physical_name,3)) v\n  WHERE 1 = 1\n  AND $__timeFilter(fs.snapshot_time)\n    and snapshot_time >= dateadd(minute,-15,getutcdate())\n  AND [sql_instance] = '$sql_instance'\n  AND database_name IN ($database)\n  GROUP BY fs.snapshot_time \n  , left(upper([file_physical_name]),2) + ' ' + isnull(v.label,'')\nORDER BY\n  time ASC"
      }
     ]
    }
   ]
  }
 ]
}