{
 "title": "Wait Events",
 "tags": [ "SQLWATCH" ],
 "time": {
  "from": "now-24h",
  "to": "now﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿"
 },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   { "name": "Waits", "label": "Group Waits By", "query": "Category,Type" },
   { "name": "QueryPlanHash", "label": "Query Plan Hash", "query": "﻿﻿0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Events with wait longer than 1 second as registered by the Extended Event Session. \nPlease note that the fact that the query is waiting for a resource, does not mean that it is the query's fault. It could be a dozen of other \"heavy\" queries causing this particular query to wait. "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wait Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for wait events\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nSELECT \n      [time]= event_time\n      ,[Wait Type] = case when ''$Waits'' = ''Category'' then [wait_category] else [wait_type] end\n      ,[Wait Duration] = sum([duration])\n  FROM [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_xes_wait_events]\n  WHERE $__timeFilter(event_time)\n  AND [sql_instance] = ''$sql_instance''\n  group by event_time,case when ''$Waits'' = ''Category'' then [wait_category] else [wait_type] end\nORDER BY time ASC'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "-- Dynamic query using linked server for wait events details\nDECLARE @linked_server_name NVARCHAR(255), @database_name NVARCHAR(128)\nSELECT @linked_server_name = ISNULL(linked_server_name, sql_instance),\n       @database_name = sqlwatch_database_name\nFROM [dbo].[sqlwatch_config_sql_instance] \nWHERE sql_instance = '$sql_instance'\n\nDECLARE @sql NVARCHAR(MAX) = '\nselect \t event_time\t\n\t,wait_type\t\n\t,wait_category\t\n\t,duration\t\n\t,signal_duration\t\n\t,session_id\t\n\t,username\t\n\t,client_hostname\t\n\t,client_app_name\t\n\t,database_name\t\n\t,sql_instance\t\n\t,snapshot_time\t\n\t,sql_text\n\t,query_plan_hash=convert(varchar(max),isnull(query_plan_hash,0),2)\nfrom [' + @linked_server_name + '].[' + @database_name + '].[dbo].[vw_sqlwatch_report_fact_xes_wait_events] \nWHERE [sql_instance] = ''$sql_instance''\nAND $__timeFilter(event_time)'\n\nEXEC sp_executesql @sql"
    }
   ]
  },
  {
   "title": "SQL Text from Plan Hash",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select distinct time=getdate(),convert(varchar(max),sql_text)\nfrom [dbo].[vw_sqlwatch_report_fact_xes_wait_events] \nwhere $__timeFilter(event_time)\nand convert(varchar(max),query_plan_hash,2) = right('$QueryPlanHash',len('$QueryPlanHash')-2)"
    }
   ]
  }
 ]
}